select * from customer limit 20

ALTER TABLE customer
RENAME COLUMN "purchase_amount_(usd)" TO purchased_amount;


--Total revenue generated by Male vs Female customers
select gender, sum(purchased_amount) as revenue 
from customer
group by gender

--used discount but still spent more than average
select customer_id, purchased_amount
from customer
where discount_applied = 'Yes'
And purchased_amount >= (select AVG(purchased_amount) from customer)

--top 5 products with highest average rating
select item_purchased, Round(avg(review_rating::numeric),2) as "Average Product Rating"
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5

--Average purchase amounts in standard and express delivery
select shipping_type, Round(avg(purchased_amount),2)
from customer
where shipping_type in ('Standard','Express')
group by shipping_type

--Do subscribed customer spend more? compare avg spend and total revenue
--Between subscribers and non-subscribers
select subscription_status,
count(customer_id) as total_customers,
round(avg(purchased_amount),2) as Average_spend,
round(sum(purchased_amount),2) as total_revenue
from customer
group by subscription_status
order by total_revenue, Average_spend desc

--5 products that have the highest percentage of purchase with discounts applied
select item_purchased,
round(100 * sum(case when discount_applied = 'Yes' Then 1 else 0 end)/count(*) ,2) as discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5 

--Segment customers into new, returning and loyal based on their
--total previous purchases, and show the count of each segment
with customer_type as( 
select customer_id, previous_purchases,
Case
	when previous_purchases = 1 then 'New'
	when previous_purchases between 2 and 10 then 'Returning'
	else 'Loyal'
	end as customer_segment
from customer	
)

select customer_segment, count(*) as "Number of customers"
from customer_type
group by customer_segment

--top 3 most purchased products within each category
with item_counts as (
select category,
item_purchased,
count(customer_id) as total_orders,
Row_Number() over(partition by category order by count(customer_id)Desc) as item_rank
from customer
group by category, item_purchased
)

select item_rank, category, item_purchased, total_orders
from item_counts
where item_rank <=3

--are customers who are repeated buyers also likely to subscribe
--more than 5 previous purchases
select subscription_status,
count(customer_id) as repeat_buyers
from customer
where previous_purchases > 5
group by subscription_status

--revenue by age group
select age_group, sum(purchased_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc